Repository supriya46788/Research-Paper-Organizer, pull requests merged in 2025-08, with the labels that each got.

#52 improve color scheme
  style.css
Labels: GSSoC'25, level-1

#176 Add Smooth Animations to Enhance UI/UX
  css/style.css
Labels: enhancement, good first issue, GSSoC'25, level-1

#234 Fixed Missing Research and Tools Cards on Tools Page
  tools.html
Labels: GSSoC'25, level-2

#285 Added email domain validation
  js/auth.js
Labels: GSSoC'25, level-2

#305 Fixed : Enhancement : Adding hover effects on Home page
  landing.css
Labels: enhancement, GSSoC'25, level-2

#325 Responsiveness for landing page
  index.html
  landing.css
  landing.js
Labels: enhancement, GSSoC'25, level-2
