Repository supriya46788/Research-Paper-Organizer, pull requests merged in 2025-09, with the labels that each got.

#401 Fixed duplicate "Resources" block in footer section
  index.html
Labels: GSSoC'25, level-2

#428 Add back to top redirection in readme.md
  docs/README.md
Labels: documentation, GSSoC'25, level-1

#456 Progress Bar Updated
  signup.html
Labels: GSSoC'25, level-1

#552 Updating the documentation by adding tech stack,project structure and…
  docs/README.md
Labels: GSSoC'25, level-1

#572 fix colors In toggle button and contact navBar in light theme and added leaderBoard
  about.html
  css/about.css
  css/contact.css
  css/style.css
Labels: GSSoC'25, level-2

#622 Enhanced CoC with badges, emojis, and GIFs
  docs/CONTRIBUTING.md
Labels: GSSoC'25, level-1
